# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/macpeecee/Desktop/projects/Dolphin-Matchmaking-Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/macpeecee/Desktop/projects/Dolphin-Matchmaking-Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macpeecee/Desktop/projects/Dolphin-Matchmaking-Server/CMakeFiles /Users/macpeecee/Desktop/projects/Dolphin-Matchmaking-Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macpeecee/Desktop/projects/Dolphin-Matchmaking-Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dolphin_Matchmaking

# Build rule for target.
Dolphin_Matchmaking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dolphin_Matchmaking
.PHONY : Dolphin_Matchmaking

# fast build rule for target.
Dolphin_Matchmaking/fast:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/build
.PHONY : Dolphin_Matchmaking/fast

source/Connector.o: source/Connector.cpp.o

.PHONY : source/Connector.o

# target to build an object file
source/Connector.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Connector.cpp.o
.PHONY : source/Connector.cpp.o

source/Connector.i: source/Connector.cpp.i

.PHONY : source/Connector.i

# target to preprocess a source file
source/Connector.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Connector.cpp.i
.PHONY : source/Connector.cpp.i

source/Connector.s: source/Connector.cpp.s

.PHONY : source/Connector.s

# target to generate assembly for a file
source/Connector.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Connector.cpp.s
.PHONY : source/Connector.cpp.s

source/Dolphin-Matchmaking-Server.o: source/Dolphin-Matchmaking-Server.cpp.o

.PHONY : source/Dolphin-Matchmaking-Server.o

# target to build an object file
source/Dolphin-Matchmaking-Server.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Dolphin-Matchmaking-Server.cpp.o
.PHONY : source/Dolphin-Matchmaking-Server.cpp.o

source/Dolphin-Matchmaking-Server.i: source/Dolphin-Matchmaking-Server.cpp.i

.PHONY : source/Dolphin-Matchmaking-Server.i

# target to preprocess a source file
source/Dolphin-Matchmaking-Server.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Dolphin-Matchmaking-Server.cpp.i
.PHONY : source/Dolphin-Matchmaking-Server.cpp.i

source/Dolphin-Matchmaking-Server.s: source/Dolphin-Matchmaking-Server.cpp.s

.PHONY : source/Dolphin-Matchmaking-Server.s

# target to generate assembly for a file
source/Dolphin-Matchmaking-Server.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Dolphin-Matchmaking-Server.cpp.s
.PHONY : source/Dolphin-Matchmaking-Server.cpp.s

source/GeoLocation.o: source/GeoLocation.cpp.o

.PHONY : source/GeoLocation.o

# target to build an object file
source/GeoLocation.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/GeoLocation.cpp.o
.PHONY : source/GeoLocation.cpp.o

source/GeoLocation.i: source/GeoLocation.cpp.i

.PHONY : source/GeoLocation.i

# target to preprocess a source file
source/GeoLocation.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/GeoLocation.cpp.i
.PHONY : source/GeoLocation.cpp.i

source/GeoLocation.s: source/GeoLocation.cpp.s

.PHONY : source/GeoLocation.s

# target to generate assembly for a file
source/GeoLocation.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/GeoLocation.cpp.s
.PHONY : source/GeoLocation.cpp.s

source/Logger.o: source/Logger.cpp.o

.PHONY : source/Logger.o

# target to build an object file
source/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Logger.cpp.o
.PHONY : source/Logger.cpp.o

source/Logger.i: source/Logger.cpp.i

.PHONY : source/Logger.i

# target to preprocess a source file
source/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Logger.cpp.i
.PHONY : source/Logger.cpp.i

source/Logger.s: source/Logger.cpp.s

.PHONY : source/Logger.s

# target to generate assembly for a file
source/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Logger.cpp.s
.PHONY : source/Logger.cpp.s

source/Matchmaker.o: source/Matchmaker.cpp.o

.PHONY : source/Matchmaker.o

# target to build an object file
source/Matchmaker.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Matchmaker.cpp.o
.PHONY : source/Matchmaker.cpp.o

source/Matchmaker.i: source/Matchmaker.cpp.i

.PHONY : source/Matchmaker.i

# target to preprocess a source file
source/Matchmaker.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Matchmaker.cpp.i
.PHONY : source/Matchmaker.cpp.i

source/Matchmaker.s: source/Matchmaker.cpp.s

.PHONY : source/Matchmaker.s

# target to generate assembly for a file
source/Matchmaker.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Matchmaker.cpp.s
.PHONY : source/Matchmaker.cpp.s

source/Player.o: source/Player.cpp.o

.PHONY : source/Player.o

# target to build an object file
source/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Player.cpp.o
.PHONY : source/Player.cpp.o

source/Player.i: source/Player.cpp.i

.PHONY : source/Player.i

# target to preprocess a source file
source/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Player.cpp.i
.PHONY : source/Player.cpp.i

source/Player.s: source/Player.cpp.s

.PHONY : source/Player.s

# target to generate assembly for a file
source/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Player.cpp.s
.PHONY : source/Player.cpp.s

source/PlayerInfo.o: source/PlayerInfo.cpp.o

.PHONY : source/PlayerInfo.o

# target to build an object file
source/PlayerInfo.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerInfo.cpp.o
.PHONY : source/PlayerInfo.cpp.o

source/PlayerInfo.i: source/PlayerInfo.cpp.i

.PHONY : source/PlayerInfo.i

# target to preprocess a source file
source/PlayerInfo.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerInfo.cpp.i
.PHONY : source/PlayerInfo.cpp.i

source/PlayerInfo.s: source/PlayerInfo.cpp.s

.PHONY : source/PlayerInfo.s

# target to generate assembly for a file
source/PlayerInfo.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerInfo.cpp.s
.PHONY : source/PlayerInfo.cpp.s

source/PlayerQueue.o: source/PlayerQueue.cpp.o

.PHONY : source/PlayerQueue.o

# target to build an object file
source/PlayerQueue.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerQueue.cpp.o
.PHONY : source/PlayerQueue.cpp.o

source/PlayerQueue.i: source/PlayerQueue.cpp.i

.PHONY : source/PlayerQueue.i

# target to preprocess a source file
source/PlayerQueue.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerQueue.cpp.i
.PHONY : source/PlayerQueue.cpp.i

source/PlayerQueue.s: source/PlayerQueue.cpp.s

.PHONY : source/PlayerQueue.s

# target to generate assembly for a file
source/PlayerQueue.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/PlayerQueue.cpp.s
.PHONY : source/PlayerQueue.cpp.s

source/Server.o: source/Server.cpp.o

.PHONY : source/Server.o

# target to build an object file
source/Server.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Server.cpp.o
.PHONY : source/Server.cpp.o

source/Server.i: source/Server.cpp.i

.PHONY : source/Server.i

# target to preprocess a source file
source/Server.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Server.cpp.i
.PHONY : source/Server.cpp.i

source/Server.s: source/Server.cpp.s

.PHONY : source/Server.s

# target to generate assembly for a file
source/Server.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/Server.cpp.s
.PHONY : source/Server.cpp.s

source/stdafx.o: source/stdafx.cpp.o

.PHONY : source/stdafx.o

# target to build an object file
source/stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/stdafx.cpp.o
.PHONY : source/stdafx.cpp.o

source/stdafx.i: source/stdafx.cpp.i

.PHONY : source/stdafx.i

# target to preprocess a source file
source/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/stdafx.cpp.i
.PHONY : source/stdafx.cpp.i

source/stdafx.s: source/stdafx.cpp.s

.PHONY : source/stdafx.s

# target to generate assembly for a file
source/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/Dolphin_Matchmaking.dir/build.make CMakeFiles/Dolphin_Matchmaking.dir/source/stdafx.cpp.s
.PHONY : source/stdafx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Dolphin_Matchmaking"
	@echo "... source/Connector.o"
	@echo "... source/Connector.i"
	@echo "... source/Connector.s"
	@echo "... source/Dolphin-Matchmaking-Server.o"
	@echo "... source/Dolphin-Matchmaking-Server.i"
	@echo "... source/Dolphin-Matchmaking-Server.s"
	@echo "... source/GeoLocation.o"
	@echo "... source/GeoLocation.i"
	@echo "... source/GeoLocation.s"
	@echo "... source/Logger.o"
	@echo "... source/Logger.i"
	@echo "... source/Logger.s"
	@echo "... source/Matchmaker.o"
	@echo "... source/Matchmaker.i"
	@echo "... source/Matchmaker.s"
	@echo "... source/Player.o"
	@echo "... source/Player.i"
	@echo "... source/Player.s"
	@echo "... source/PlayerInfo.o"
	@echo "... source/PlayerInfo.i"
	@echo "... source/PlayerInfo.s"
	@echo "... source/PlayerQueue.o"
	@echo "... source/PlayerQueue.i"
	@echo "... source/PlayerQueue.s"
	@echo "... source/Server.o"
	@echo "... source/Server.i"
	@echo "... source/Server.s"
	@echo "... source/stdafx.o"
	@echo "... source/stdafx.i"
	@echo "... source/stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

